### ISSUE TITLE
Create Auto Jump feature

### ISSUE THREAD

**Issue by HSQuillin** [BlueStaggo/VoxelThingJava#3]
Description
---
This feature would be the first accessibility feature in Voxel Thing, which allows a function that toggles jumping automatically for the character as a stored setting on the user's end. This can be enabled/disabled in its current state with `F7`. This is extremely commonly found in platformers in the context of 3D environments.

Implementation
---
This would calculate the distance of voxels in front of the player (ideally one) to get context of whether or not the jump should perform. This would add a new method such as `getFrontPosition` and modify `jumpPressed` which calls the math to check the context in front of the player, and the `onGameUpdate` method to add a controller check for a keybind. This would also modify `Game.java` to include the new feature as a property, under `var options = new Properties();` and write to `opt.txt`.

Summary
---
Accessibility feature which allows your character to jump automatically.

**Comment by BlueStaggo** [comment]
Once I add in a proper options menu, I'll make sure to add this in.

**Comment by ArshKumar84** [comment]
Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?

**Comment by DexrnZacAttack** [comment]
> Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?

uhhh learn C# :trollface: 
nah but actually afaik the project is being rewritten in C#

**Comment by TwigWallder** [comment]
> Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?

If you want to participate in other open source projects I invite you to watch this [video](https://www.youtube.com/watch?v=CML6vfKjQss)which explains the process very well. I hope this can help you.


> > Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?
> 
> uhhh learn C# :trollface: nah but actually afaik the project is being rewritten in C#

If the project is "dead" I advise you to archive it and close this issue so that there are no other requests of this style.

**Comment by shinevee** [comment]
> If the project is "dead" I advise you to archive it and close this issue so that there are no other requests of this style.
I think he's just gonna make a new branch once the C# rewrite has a build that matches the current java one

**Comment by ArshKumar84** [comment]
> > Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?
> 
> If you want to participate in other open source projects I invite you to watch this [video](https://www.youtube.com/watch?v=CML6vfKjQss)which explains the process very well. I hope this can help you.
> 
> > > Hello! I have experience in Java Spring development and have previously developed REST APIs in Java. I'd love to contribute to this project and help enhance its functionality. Could you please guide me on how to get started?
> > 
> > 
> > uhhh learn C# :trollface: nah but actually afaik the project is being rewritten in C#
> 
> If the project is "dead" I advise you to archive it and close this issue so that there are no other requests of this style.

If you come across any repositories that use Spring to build REST APIs, please let me know—it would be really helpful.

**Comment by BlueStaggo** [comment]
Yeah my plan is to archive this repo and make a new one for the C# version. Things are going smoothly for the C# port btw.
